/**
 * @file game/missiles/missiles.hpp
 *
 * Interface of missile functionality.
 */
#pragma once

#include <cstdint>
#include <list>
#include <optional>

#include "engine/attributes.hpp"
#include "engine/math/displacement.hpp"
#include "engine/math/point.hpp"
#include "engine/math/world_tile.hpp"
#include "game/monsters/monsters.hpp"
#include "game/players/players.hpp"
#include "tables/misdat.h"
#include "tables/spelldat.h"
#include "utils/is_of.hpp"

namespace devilution {

constexpr WorldTilePosition GolemHoldingCell = Point { 1, 0 };

struct MissilePosition {
	
	Displacement offset; // Sprite's pixel offset from tile.
	Displacement velocity; // Pixel velocity while moving
	Displacement traveled; // Pixels traveled as a numerator of 65,536.
	WorldTilePosition tile;
	WorldTilePosition start; // Start position
	WorldTilePosition tileForRendering; // Specifies the location (tile) while rendering
	Displacement offsetForRendering; // Specifies the location (offset) while rendering

	// Stops the missile (set velocity to zero and set offset to last renderer location;
	// shouldn't matter because the missile doesn't move anymore)
	void StopMissile()
	{
		velocity = {};
		if (tileForRendering == tile)
			offset = offsetForRendering;
	}
};

enum class MissileSource : uint8_t {
	Player,
	Monster,
	Trap,
};

enum class GuardianFrame : uint8_t {
	Start = 0,
	Idle = 1,
	Attack = 2,
};

enum class AcidPuddleFrame : uint8_t {
	Idle = 0,
	End = 1,
};

enum class FireWallFrame : uint8_t {
	Start = 0,
	Idle = 1,
};

enum class PortalFrame : uint8_t {
	Start = 0,
	Idle = 1,
};

enum class RedPortalFrame : uint8_t {
	Start = 0,
	Idle = 1,
};

struct Missile {
	MissileID _mitype; // Type of projectile
	MissilePosition position;

private:
	int _mimfnum; // The direction of the missile (direction enum)

public:
	int _mispllvl;
	bool _miDelFlag; // Indicate whether the missile should be deleted
	MissileGraphicID _miAnimType;
	MissileGraphicsFlags _miAnimFlags;
	OptionalClxSpriteList _miAnimData;
	int _miAnimDelay; // Tick length of each frame in the current animation
	int _miAnimLen;   // Number of frames in current animation

	// TODO: This field is no longer used and is always equal to
	// (*_miAnimData)[0].width()
	uint16_t _miAnimWidth;

	int16_t _miAnimWidth2;
	int _miAnimCnt; // Increases by one each game tick, counting how close we are to _pAnimDelay
	int _miAnimAdd;
	int _miAnimFrame; // Current frame of animation + 1.
	bool _miDrawFlag;
	bool _miLightFlag;
	bool _miPreFlag;
	uint32_t _miUniqTrans;
	int duration; // Time to live for the missile in game ticks; once 0, the missile will be marked for deletion via _miDelFlag */
	int _misource;
	mienemy_type _micaster;
	int _midam;
	bool _miHitFlag;
	int _midist; // Used for arrows to measure distance travelled (increases by 1 each game tick). Higher value is a penalty for accuracy calculation when hitting enemy
	int _mlid;
	int _mirnd;
	union {
		struct { int var1, var2, var3, var4, var5, var6, var7; }; // Backward compat (offsets 0-24)
		int raw[7];                                  // Raw array access (offsets 0-24)
		struct { int monsterId, state, frameCounter; } guardian; // var1-var3
		struct { int x, y, level; } portal;          // var1-var3: town portal destination
		struct { int runeType, fromX, fromY; } rune; // var1-var3: rune parameters
		struct { int direction, monsterIdx, state; } wall; // var1-var3: wall control
		struct { int range, monsterIdx, damage; } inferno; // var1-var3: inferno
		struct { int centerX, centerY, totalCount; } nova; // var1-var3: nova/immolation
		struct { int srcX, srcY, wallDir; } fireWall; // var1-var3: firewall
		struct { int srcMonsterId, maxHits; } golem;  // var1-var2: golem
		struct { int id; } simple;                    // var1: single-id usage
		struct { int srcX, srcY, pad1, destX, destY; } projectile; // var1-var5: projectile target
		struct { int monsterId, jumps, pad1, destX, destY; } chain; // var1-var5: chain lightning
		struct { int monsterId, pad1, pad2, destX, destY; } lightning; // var1, var4-var5
	};
	bool limitReached;
	int16_t lastCollisionTargetHash; // For moving missiles lastCollisionTargetHash contains the last entity
									 // (player or monster) that was checked in CheckMissileCol (needed to
									 // avoid multiple hits for a entity at the same tile).

	// Was the missile generated by a trap?
	[[nodiscard]] bool IsTrap() const
	{
		return _misource == -1;
	}

	[[nodiscard]] Player *sourcePlayer()
	{
		if (IsNoneOf(_micaster, TARGET_BOTH, TARGET_MONSTERS) || _misource == -1)
			return nullptr;
		return &Players[_misource];
	}

	[[nodiscard]] Monster *sourceMonster()
	{
		if (_micaster != TARGET_PLAYERS || _misource == -1)
			return nullptr;
		return &Monsters[_misource];
	}

	[[nodiscard]] bool isSameSource(Missile &missile)
	{
		return sourceType() == missile.sourceType() && _misource == missile._misource;
	}

	MissileSource sourceType()
	{
		if (_misource == -1)
			return MissileSource::Trap;
		if (_micaster == TARGET_PLAYERS)
			return MissileSource::Monster;
		return MissileSource::Player;
	}

	void setAnimation(MissileGraphicID animtype);

	// Sets the missile sprite to the given sheet frame
	void setFrameGroupRaw(int frameGroup)
	{
		_mimfnum = frameGroup;
		setAnimation(_miAnimType);
	}

	void setDefaultFrameGroup()
	{
		setFrameGroupRaw(0);
	}

	template <typename FrameEnum>
	void setFrameGroup(FrameEnum frameGroup)
	{
		setFrameGroupRaw(static_cast<int>(frameGroup));
	}

	// brief Sets the sprite for this missile so it matches the given facing Direction
	void setDirection(Direction dir)
	{
		setFrameGroupRaw(static_cast<int>(dir));
	}

	// Sets the sprite for this missile so it matches the given Direction16
	// (Desired facing at a 22.8125 degree resolution)
	void setDirection(Direction16 dir)
	{
		setFrameGroupRaw(static_cast<int>(dir));
	}

	int getFrameGroupRaw() const
	{
		return _mimfnum;
	}

	template <typename FrameEnum>
	FrameEnum getFrameGroup() const
	{
		static_assert(std::is_enum_v<FrameEnum>, "Frame group must be an enum");
		return static_cast<FrameEnum>(_mimfnum);
	}

	[[nodiscard]] Direction getDirection() const
	{
		return static_cast<Direction>(_mimfnum);
	}

	[[nodiscard]] Direction16 getDirection16() const
	{
		return static_cast<Direction16>(_mimfnum);
	}
};

extern std::list<Missile> Missiles;
extern bool MissilePreFlag;

DamageRange GetDamageAmt(SpellID spell, int spellLevel);

/**
 * @brief Returns the direction a vector from p1(x1, y1) to p2(x2, y2) is pointing to.
 *
 * @code{.unparsed}
 *      W  sW  SW   Sw  S
 *              ^
 *     nW       |       Se
 *              |
 *     NW ------+-----> SE
 *              |
 *     Nw       |       sE
 *              |
 *      N  Ne  NE   nE  E
 * @endcode
 *
 * @param p1 The point from which the vector starts.
 * @param p2 The point from which the vector ends.
 * @return the direction of the p1->p2 vector
 */
Direction16 GetDirection16(Point p1, Point p2);
bool MonsterTrapHit(Monster &monster, int mindam, int maxdam, int dist, MissileID t, DamageType damageType, bool shift);
bool PlayerMHit(Player &player, Monster *monster, int dist, int mind, int maxd, MissileID mtype, DamageType damageType, bool shift, DeathReason deathReason, bool *blocked);

// Could the missile collide with solid objects? (like walls or closed doors)
bool IsMissileBlockedByTile(Point tile);

void InitMissiles();

struct AddMissileParameter {
	WorldTilePosition dst;
	Direction midir;
	Missile *pParent;
	bool spellFizzled;
};

void AddOpenNest(Missile &missile, AddMissileParameter &parameter);
void AddRuneOfFire(Missile &missile, AddMissileParameter &parameter);
void AddRuneOfLight(Missile &missile, AddMissileParameter &parameter);
void AddRuneOfNova(Missile &missile, AddMissileParameter &parameter);
void AddRuneOfImmolation(Missile &missile, AddMissileParameter &parameter);
void AddRuneOfStone(Missile &missile, AddMissileParameter &parameter);
void AddReflect(Missile &missile, AddMissileParameter &parameter);
void AddBerserk(Missile &missile, AddMissileParameter &parameter);
void AddHorkSpawn(Missile &missile, AddMissileParameter &parameter);
void AddJester(Missile &missile, AddMissileParameter &parameter);
void AddStealPotions(Missile &missile, AddMissileParameter &parameter);
void AddStealMana(Missile &missile, AddMissileParameter &parameter);
void AddSpectralArrow(Missile &missile, AddMissileParameter &parameter);
void AddWarp(Missile &missile, AddMissileParameter &parameter);
void AddLightningWall(Missile &missile, AddMissileParameter &parameter);
void AddBigExplosion(Missile &missile, AddMissileParameter &parameter);
void AddImmolation(Missile &missile, AddMissileParameter &parameter);
void AddLightningBow(Missile &missile, AddMissileParameter &parameter);
void AddMana(Missile &missile, AddMissileParameter &parameter);
void AddMagi(Missile &missile, AddMissileParameter &parameter);
void AddRingOfFire(Missile &missile, AddMissileParameter &parameter);
void AddSearch(Missile &missile, AddMissileParameter &parameter);
void AddChargedBoltBow(Missile &missile, AddMissileParameter &parameter);
void AddElementalArrow(Missile &missile, AddMissileParameter &parameter);
void AddArrow(Missile &missile, AddMissileParameter &parameter);
void AddPhasing(Missile &missile, AddMissileParameter &parameter);
void AddFirebolt(Missile &missile, AddMissileParameter &parameter);
void AddMagmaBall(Missile &missile, AddMissileParameter &parameter);
void AddTeleport(Missile &missile, AddMissileParameter &parameter);
void AddNovaBall(Missile &missile, AddMissileParameter &parameter);
void AddFireWall(Missile &missile, AddMissileParameter &parameter);

void AddFireball(Missile &missile, AddMissileParameter &parameter);
void AddLightningControl(Missile &missile, AddMissileParameter &parameter);
void AddLightning(Missile &missile, AddMissileParameter &parameter);
void AddMissileExplosion(Missile &missile, AddMissileParameter &parameter);
void AddWeaponExplosion(Missile &missile, AddMissileParameter &parameter);
void AddTownPortal(Missile &missile, AddMissileParameter &parameter);
void AddFlashBottom(Missile &missile, AddMissileParameter &parameter);
void AddFlashTop(Missile &missile, AddMissileParameter &parameter);
void AddManaShield(Missile &missile, AddMissileParameter &parameter);
void AddFlameWave(Missile &missile, AddMissileParameter &parameter);
void AddGuardian(Missile &missile, AddMissileParameter &parameter);
void AddChainLightning(Missile &missile, AddMissileParameter &parameter);
void AddRhino(Missile &missile, AddMissileParameter &parameter);
void AddGenericMagicMissile(Missile &missile, AddMissileParameter &parameter);
void AddAcid(Missile &missile, AddMissileParameter &parameter);
void AddAcidPuddle(Missile &missile, AddMissileParameter &parameter);
void AddStoneCurse(Missile &missile, AddMissileParameter &parameter);
void AddGolem(Missile &missile, AddMissileParameter &parameter);
void AddApocalypseBoom(Missile &missile, AddMissileParameter &parameter);
void AddHealing(Missile &missile, AddMissileParameter &parameter);
void AddHealOther(Missile &missile, AddMissileParameter &parameter);
void AddElemental(Missile &missile, AddMissileParameter &parameter);
void AddIdentify(Missile &missile, AddMissileParameter &parameter);
void AddWallControl(Missile &missile, AddMissileParameter &parameter);
void AddInfravision(Missile &missile, AddMissileParameter &parameter);
void AddFlameWaveControl(Missile &missile, AddMissileParameter &parameter);
void AddNova(Missile &missile, AddMissileParameter &parameter);
void AddRage(Missile &missile, AddMissileParameter &parameter);
void AddItemRepair(Missile &missile, AddMissileParameter &parameter);
void AddStaffRecharge(Missile &missile, AddMissileParameter &parameter);
void AddTrapDisarm(Missile &missile, AddMissileParameter &parameter);
void AddApocalypse(Missile &missile, AddMissileParameter &parameter);
void AddInferno(Missile &missile, AddMissileParameter &parameter);
void AddInfernoControl(Missile &missile, AddMissileParameter &parameter);
void AddChargedBolt(Missile &missile, AddMissileParameter &parameter);
void AddHolyBolt(Missile &missile, AddMissileParameter &parameter);
void AddResurrect(Missile &missile, AddMissileParameter &parameter);
void AddResurrectBeam(Missile &missile, AddMissileParameter &parameter);
void AddTelekinesis(Missile &missile, AddMissileParameter &parameter);
void AddBoneSpirit(Missile &missile, AddMissileParameter &parameter);
void AddRedPortal(Missile &missile, AddMissileParameter &parameter);
void AddDiabloApocalypse(Missile &missile, AddMissileParameter &parameter);
Missile *AddMissile(WorldTilePosition src, WorldTilePosition dst, Direction midir, MissileID mitype,
    mienemy_type micaster, int id, int midam, int spllvl,
    Missile *parent = nullptr, std::optional<SfxID> lSFX = std::nullopt);
inline Missile *AddMissile(WorldTilePosition src, WorldTilePosition dst, Direction midir, MissileID mitype,
    mienemy_type micaster, const Player &player, int midam, int spllvl,
    Missile *parent = nullptr, std::optional<SfxID> lSFX = std::nullopt)
{
	return AddMissile(src, dst, midir, mitype, micaster, player.getId(), midam, spllvl, parent, lSFX);
}
inline Missile *AddMissile(WorldTilePosition src, WorldTilePosition dst, Direction midir, MissileID mitype,
    mienemy_type micaster, const Monster &monster, int midam, int spllvl,
    Missile *parent = nullptr, std::optional<SfxID> lSFX = std::nullopt)
{
	return AddMissile(src, dst, midir, mitype, micaster, static_cast<int>(monster.getId()), midam, spllvl, parent, lSFX);
}
void ProcessElementalArrow(Missile &missile);
void ProcessArrow(Missile &missile);
void ProcessGenericProjectile(Missile &missile);
void ProcessNovaBall(Missile &missilei);
void ProcessAcidPuddle(Missile &missile);
void ProcessFireWall(Missile &missile);
void ProcessFireball(Missile &missile);
void ProcessHorkSpawn(Missile &missile);
void ProcessRune(Missile &missile);
void ProcessLightningWall(Missile &missile);
void ProcessBigExplosion(Missile &missile);
void ProcessLightningBow(Missile &missile);
void ProcessRingOfFire(Missile &missile);
void ProcessSearch(Missile &missile);
void ProcessImmolation(Missile &missile);
void ProcessSpectralArrow(Missile &missile);
void ProcessLightningControl(Missile &missile);
void ProcessLightning(Missile &missile);
void ProcessTownPortal(Missile &missile);
void ProcessFlashBottom(Missile &missile);
void ProcessFlashTop(Missile &missile);
void ProcessFlameWave(Missile &missile);
void ProcessGuardian(Missile &missile);
void ProcessChainLightning(Missile &missile);
void ProcessWeaponExplosion(Missile &missile);
void ProcessMissileExplosion(Missile &missile);
void ProcessAcidSplate(Missile &missile);
void ProcessTeleport(Missile &missile);
void ProcessStoneCurse(Missile &missile);
void ProcessApocalypseBoom(Missile &missile);
void ProcessRhino(Missile &missile);
void ProcessWallControl(Missile &missile);
void ProcessInfravision(Missile &missile);
void ProcessApocalypse(Missile &missile);
void ProcessFlameWaveControl(Missile &missile);
void ProcessNova(Missile &missile);
void ProcessRage(Missile &missile);
void ProcessInferno(Missile &missile);
void ProcessInfernoControl(Missile &missile);
void ProcessChargedBolt(Missile &missile);
void ProcessHolyBolt(Missile &missile);
void ProcessElemental(Missile &missile);
void ProcessBoneSpirit(Missile &missile);
void ProcessResurrectBeam(Missile &missile);
void ProcessRedPortal(Missile &missile);
void ProcessMissiles();
void SetUpMissileAnimationData();
void RedoMissileFlags();

#ifdef BUILD_TESTING
void TestRotateBlockedMissile(Missile &missile);
#endif

} // namespace devilution
