using Devilution.Protocol.V1;

namespace Devilution.Server.Commands;

/** Supplies transient gameplay events generated by accepted commands. */
public interface IAuthoritativeEventProvider
{
    EventBatch? DrainEvents(string sessionId, uint entityId, ulong tick);
}
